# Generated by Django 3.0.7 on 2020-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField(unique=True)),
                ('product_name', models.CharField(default='', max_length=150)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('food', 'Food & Beverages'), ('accessories', 'Accessories'), ('health', 'Healthcare')], max_length=20)),
                ('product_price', models.IntegerField(default=0)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
